name: Smoke test "universal-arm64" build

on: 
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/universal-arm64/**
      - .github/universal-arm64/smoke-universal-arm64.yaml
      - .github/actions/**
      - build/**
jobs:
  smoke-test:
    name: Smoke test
    runs-on: devcontainer-image-builder-ubuntu
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3
    - name: Smoke test
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        image: universal-arm64
        threshold: 10
